output "host" {
  value       = google_redis_instance.redis.host
  description = "The IP address of the private Redis instance"
}

output "port" {
  value       = google_redis_instance.redis.port
  description = "The port of the private Redis instance"
}

output "auth_string" {
  value       = google_redis_instance.redis.auth_string
  description = "The autogenerated auth string used to log into Redis"
  sensitive   = true
}
